AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for FilePack API

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: filepack-api
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Remove untagged images after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  AccountId:
    Description: AWS Account ID
    Value: !Ref AWS::AccountId
  RepositoryName:
    Description: ECR Repository Name
    Value: !Ref ECRRepository
  RepositoryUri:
    Description: ECR Repository URI
    Value: !GetAtt ECRRepository.RepositoryUri
